replicas: 1

service:
  type: LoadBalancer

persistence:
  type: pvc
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  finalizers:
    - kubernetes.io/pvc-protection

adminUser: admin
adminPassword: test1234!234