server:
  enabled: true

  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    mountPath: /data
    size: 10Gi
  replicaCount: 1
  retention: "15d"

  service:
    enabled: true
    type: LoadBalancer

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'kubernetes-service-endpoints'
        honor_labels: true
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: kubernetes_name

# 리스트는 오버라이드가 안된다. extra scrape config를 넣을 수 있는가? 글고 얘는 사실 왜필요한거야 똑같이 쓴 급인데 생각해보니까?